BDB 5.2.28

diff --git a/dist/buildpkg b/dist/buildpkg
--- a/dist/buildpkg
+++ b/dist/buildpkg
@@ -13,6 +13,7 @@ die()
 CSHARP_DOC_SRC=""
 # 0 is none, 1 is local dir, 2 is remote dir
 CSHARP_DOC_LOCATION=0
+test_run=0
 
 while [ $# -gt 0 ]
 do
@@ -36,6 +37,10 @@ do
 		fi
 		CSHARP_DOC_SRC=$1
 		CSHARP_DOC_LOCATION=2;;
+	-test)
+		echo "Doing a test run - this may contain changes that aren't\
+reflected in a tag, so the package won't be reproducible."
+		test_run=1;;
 	esac
 	shift
 done
@@ -52,8 +57,7 @@ START_DIR=`pwd`
 D=`pwd`/../release
 R="$D/db-${VERSION}"
 RNC="$D/db-$VERSION.NC"
-#DOCS=`pwd`/../../docs_books
-DOCS=`pwd`/../../docs_books-5.1
+DOCS=`pwd`/../../docs_books
 DB_ADDONS=`pwd`/../../db_addons
 
 if [ ! -d $DB_ADDONS ]; then
@@ -69,6 +73,11 @@ echo "Removed old release build from $R"
 
 # Copy the files in the current tip to $R
 hg archive $R
+
+# If doing a test run, apply any local changes to the new tree.
+if [ $test_run != 0 ]; then
+	hg diff | patch -p1 -d $R
+fi
 
 echo "Created hg archive in $R"
 
@@ -124,8 +133,14 @@ else
 fi
 
 # Pull a copy of the JDBC and ODBC libraries into the package.
+# Build the ADO.NET package, including moving the ADO.NET doc built above
+# into that package.
 # Tell the script where to look for packages.
 cd $R/dist && sh s_sql_drivers ../../../..
+# Warn if s_sql_drivers didn't move its docs.
+if [ -e "$R/docs/bdb-sql-ado" ]; then
+	echo "WARNING: ADO.NET doc is still in the non ADO.NET package."
+fi
 
 cd $START_DIR
 
@@ -182,7 +197,14 @@ cd $R && find . | sort -f | uniq -ic | sed '/1 /d'
 # Create the crypto tar archive release.
 T="$D/db-$VERSION.tar.gz"
 rm -f $T
-cd $D && $TAR czf $T -find db-$VERSION -chown 100 -chgrp 100
+cd $D || die "Can't find $D"
+# Move package files in db-$VERSION/release to current directory so that
+# regular packages won't includes generated package twice.
+if [ -d "db-$VERSION/release" ]; then
+	mv db-$VERSION/release/* .
+	rm -rf db-$VERSION/release
+fi
+$TAR czf $T -find db-$VERSION -chown 100 -chgrp 100
 chmod 444 $T
 
 # Create the non-crypto tree.
diff --git a/dist/s_sql_upgrade b/dist/s_sql_upgrade
--- a/dist/s_sql_upgrade
+++ b/dist/s_sql_upgrade
@@ -27,7 +27,7 @@ for f in ../lang/sql/adapter/*.[ch]; do
 	copy_if_changes $MAKEFILE_NAME $MAKEFILE_NAME.tmp
 done
 # Update the include path so that headers in sql/adapter dir can be found.
-sed -e '/^TCC/s/-I\. -I${TOP}\/src$/& -I${TOP}\/..\/adapter/' $MAKEFILE_NAME > $MAKEFILE_NAME.tmp
+sed -e '/^TCC/s/-I\. -I${TOP}\/src/& -I${TOP}\/..\/adapter/' $MAKEFILE_NAME > $MAKEFILE_NAME.tmp
 copy_if_changes $MAKEFILE_NAME $MAKEFILE_NAME.tmp
 
 # We will be building from a different directory level, update the makefile
@@ -41,7 +41,8 @@ for f in $sqldir/../adapter/sqlite-patches/[0-9][0-9]_*.patch ; do
 		echo "Applying patch $f"
 		(cd $sqldir && patch -p0 --force --quiet) < $f
 	else
-		echo "Patch $f would fail, probably already applied. Skipping."
+		echo "Patch $f would fail. Exiting."
+		exit 1
 	fi
 done
 
diff --git a/dist/validate/s_chk_logverify b/dist/validate/s_chk_logverify
--- a/dist/validate/s_chk_logverify
+++ b/dist/validate/s_chk_logverify
@@ -16,7 +16,7 @@ s=$d/src
 
 mkdir -p $b
 
-opts="--disable-shared"
+opts="--disable-shared --enable-stl"
 echo "Building DB library, this can take a while."
 (cd $b && ../../dist/configure $opts > /dev/null && make > /dev/null) || {
 	echo 'FAIL: unable to build libdb.a'
@@ -78,17 +78,26 @@ echo Archive Tests
 
 echo "**** db_perf -c $configs/archive_fatal_hash.conf -C ****"
 rm -rf TESTDIR TESTDIR.A
+rm -f logverify.ERR
 mkdir TESTDIR TESTDIR.A
 $cmd -I -hTESTDIR -c $configs/archive_fatal_hash.conf 2>&1 > TESTDIR/OUTPUT
 $cmd -C -hTESTDIR -c $configs/archive_fatal_hash.conf 2>&1 >> TESTDIR/OUTPUT
-$lv -hTESTDIR 2>&1 >> TESTDIR/OUTPUT
+$lv -hTESTDIR 2>logverify.ERR >> TESTDIR/OUTPUT || {
+grep DB_NOTFOUND logverify.ERR >/dev/null 2>/dev/null  || \
+    echo "ERROR: expect DB_NOTFOUND in the error output"
+}
 cp TESTDIR/OUTPUT $resdir/OUTPUT.3
+
 echo "**** db_perf -c $configs/archive_fatal_btree.conf -C ****"
 rm -rf TESTDIR TESTDIR.A
+rm -f logverify.ERR
 mkdir TESTDIR TESTDIR.A
 $cmd -I -hTESTDIR -c $configs/archive_fatal_btree.conf 2>&1 > TESTDIR/OUTPUT
 $cmd -C -hTESTDIR -c $configs/archive_fatal_btree.conf 2>&1 >> TESTDIR/OUTPUT
-$lv -hTESTDIR 2>&1 >> TESTDIR/OUTPUT
+$lv -hTESTDIR 2>logverify.ERR >> TESTDIR/OUTPUT || {
+grep DB_NOTFOUND logverify.ERR >/dev/null 2>/dev/null  || \
+    echo "ERROR: expect DB_NOTFOUND in the error output"
+}
 cp TESTDIR/OUTPUT $resdir/OUTPUT.4
 
 echo "**** db_perf -c $configs/archive_btree.conf -C ****"
@@ -112,11 +121,15 @@ cp TESTDIR/OUTPUT $resdir/OUTPUT.6
 
 echo "**** db_perf -c $configs/crash_test_2.conf ****"
 rm -rf TESTDIR TESTDIR.A
+rm -f logverify.ERR
 mkdir TESTDIR TESTDIR.A
 $cmd -I -hTESTDIR -c $configs/crash_test_2.conf 2>&1 > TESTDIR/OUTPUT
 $cmd -hTESTDIR -c $configs/crash_test_2.conf 2>&1 >> TESTDIR/OUTPUT
 rm TESTDIR/__db.0* # Remove region files because the environment is corrupted.
-$lv -hTESTDIR 2>&1 >> TESTDIR/OUTPUT
+$lv -hTESTDIR 2>logverify.ERR >> TESTDIR/OUTPUT || {
+grep DB_NOTFOUND logverify.ERR >/dev/null 2>/dev/null  || \
+    echo "ERROR: expect DB_NOTFOUND in the error output"
+}
 cp TESTDIR/OUTPUT $resdir/OUTPUT.7
 
 echo "**** db_perf -c $configs/crash_test_3.conf ****"
@@ -128,20 +141,20 @@ rm TESTDIR/__db.0* # Remove region files because the environment is corrupted.
 $lv -hTESTDIR 2>&1 >> TESTDIR/OUTPUT
 cp TESTDIR/OUTPUT $resdir/OUTPUT.8
 
-echo "**** db_perf -s 2 -c $configs/crash_test_1.conf ****"
+echo "**** db_perf -S 2 -c $configs/crash_test_1.conf ****"
 rm -rf TESTDIR TESTDIR.A
 mkdir TESTDIR TESTDIR.A
-$cmd -I -hTESTDIR -s 2 -c $configs/crash_test_1.conf 2>&1 > TESTDIR/OUTPUT
-$cmd -hTESTDIR -s 2 -c $configs/crash_test_1.conf 2>&1 >> TESTDIR/OUTPUT
+$cmd -I -hTESTDIR -S 2 -c $configs/crash_test_1.conf 2>&1 > TESTDIR/OUTPUT
+$cmd -hTESTDIR -S 2 -c $configs/crash_test_1.conf 2>&1 >> TESTDIR/OUTPUT
 rm TESTDIR/__db.0* # Remove region files because the environment is corrupted.
 $lv -hTESTDIR 2>&1 >> TESTDIR/OUTPUT
 cp TESTDIR/OUTPUT $resdir/OUTPUT.9
 
-echo "**** db_perf -s 1 -c $configs/crash_test_4.conf ****"
+echo "**** db_perf -S 1 -c $configs/crash_test_4.conf ****"
 rm -rf TESTDIR TESTDIR.A
 mkdir TESTDIR TESTDIR.A
-$cmd -I -hTESTDIR -s 1 -c $configs/crash_test_4.conf 2>&1 > TESTDIR/OUTPUT
-$cmd -hTESTDIR -s 1 -c $configs/crash_test_4.conf 2>&1 >> TESTDIR/OUTPUT
+$cmd -I -hTESTDIR -S 1 -c $configs/crash_test_4.conf 2>&1 > TESTDIR/OUTPUT
+$cmd -hTESTDIR -S 1 -c $configs/crash_test_4.conf 2>&1 >> TESTDIR/OUTPUT
 rm TESTDIR/__db.0* # Remove region files because the environment is corrupted.
 $lv -hTESTDIR 2>&1 >> TESTDIR/OUTPUT
 cp TESTDIR/OUTPUT $resdir/OUTPUT.10
