BDB 4.5.14

diff --git a/dist/s_vxworks b/dist/s_vxworks
--- a/dist/s_vxworks
+++ b/dist/s_vxworks
@@ -1,5 +1,5 @@
 #!/bin/sh -
-#	$Id: s_vxworks,v 12.9 2006/06/04 20:12:36 bostic Exp $
+#	$Id: s_vxworks,v 12.12 2006/06/26 17:34:19 bostic Exp $
 #
 # Build the VxWorks files.
 
@@ -89,6 +89,21 @@ f=../build_vxworks/db_int.h
 cmp $t $f > /dev/null 2>&1 ||
     (echo "Building $f" && rm -f $f && cp $t $f && chmod 444 $f)
 
+# Build the VxWorks db_config.h file.
+# We don't fail, but we complain if the vx_config.in file isn't up-to-date.
+check_config()
+{
+	egrep '^#undef' config.hin |
+	    awk '{print $2}' | sed '/^SIZEOF_/d' | sort > $s
+	(egrep '#undef' $1 | awk '{print $3}'
+	 egrep '^#define' $1 | awk '{print $2}') | sort > $t
+	cmp $s $t || {
+		echo "config.hin and $1 differ"
+		echo "<<< config.hin >>> $1"
+		diff $s $t
+	}
+}
+check_config vx_config.in
 f=../build_vxworks/db_config.h
 (echo "$msgc" && sed "s/__EDIT_DB_VERSION__/$DB_VERSION/" vx_config.in) > $t
 cmp $t $f > /dev/null 2>&1 ||
diff --git a/dist/s_windows b/dist/s_windows
--- a/dist/s_windows
+++ b/dist/s_windows
@@ -1,5 +1,5 @@
 #!/bin/sh -
-#	$Id: s_windows,v 12.17 2006/06/19 06:41:40 mjc Exp $
+#	$Id: s_windows,v 12.20 2006/07/13 06:19:45 mjc Exp $
 #
 # Build Windows include files.
 
@@ -65,8 +65,8 @@ typedef u_int32_t uintptr_t;\\
 /@platform_header@/{
 	i\\
 /*\\
- * Turn off inappropriate compiler warnings\\
- */\\
+\ * Turn off inappropriate compiler warnings\\
+\ */\\
 #ifdef _MSC_VER\\
 /*\\
 \ * This warning is explicitly disabled in Visual C++ by default.\\
@@ -143,6 +143,21 @@ f=../build_windows/db_int.h
 cmp $t $f > /dev/null 2>&1 ||
     (echo "Building $f" && rm -f $f && cp $t $f && chmod 444 $f)
 
+# Build the Windows db_config.h file.
+# We don't fail, but we complain if the win_config.in file isn't up-to-date.
+check_config()
+{
+	egrep '^#undef' config.hin |
+	    awk '{print $2}' | sed '/^SIZEOF_/d' | sort > $s
+	(egrep '#undef' $1 | awk '{print $3}'
+	 egrep '^#define' $1 | awk '{print $2}') | sed '/__STDC__/d' | sort > $t
+	cmp $s $t || {
+		echo "config.hin and $1 differ"
+		echo "<<< config.hin >>> $1"
+		diff $s $t
+	}
+}
+check_config win_config.in
 f=../build_windows/db_config.h
 (echo "$msgc" && sed "s/__EDIT_DB_VERSION__/$DB_VERSION/" win_config.in) > $t
 cmp $t $f > /dev/null 2>&1 ||
